Task/Controllers/CustomerController.cs
namespace TaskAnswer.Controllers
{

    [Authorize]
    public class CustomerController : Controller
    {
        private readonly ICustomersService _customersService;

        public CustomerController(ICustomersService customersService)
        {
            _customersService = customersService;
        }
        [HttpGet]
        public IActionResult Customer()
        {
            string Token = Request.Cookies["BearerToken"]!;
            var customer = _customersService.GetAuthorizedCustomer(Token);
            return View(customer);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var customer = _customersService.GetById(id);
            if (customer is null)
            {
                return NotFound();
            }
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                return View(customer);
            }
            var updatedCustomer = await _customersService.Edit(customer);
            if (updatedCustomer is null)
                return View(customer);
            return RedirectToAction(nameof(Customer));
        }

    }
}

Task/Controllers/ProductController.cs
namespace TaskAnswer.Controllers
{

    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductsService _productsService;

        public ProductController(IProductsService productsService)
        {
            _productsService = productsService;
        }
        [Authorize]
        public IActionResult Index()
        {
            var products = _productsService.GetAll();
            return View(products);
        }

        [HttpGet]
        public IActionResult GetAllProducts()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetPrice(int id)
        {
            decimal? price = _productsService.GetPrice(id);
            if(price == null)
            {
                return NotFound();
            }
            return Ok(price);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await _productsService.create(model);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var product = _productsService.GetById(id);
            if (product is null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Product model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var product = await _productsService.Edit(model);
            if (product is null)
                return BadRequest();
            return RedirectToAction(nameof(Index));
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var isDeleted = _productsService.Delete(id);

            return isDeleted ? Ok() : BadRequest();
        }
    }
}

Task/Controllers/PurchaseInvoiceController.cs
[Authorize]
public class PurchaseInvoiceController : Controller
{
    private readonly IProductsService _productService;
    private readonly IPurchaseInvoicesService _purchaseInvoiceService;
    public PurchaseInvoiceController(IProductsService productService, IPurchaseInvoicesService purchaseInvoiceService)
    {
        _productService = productService;
        _purchaseInvoiceService = purchaseInvoiceService;
    }

    // GET: PurchaseInvoice/Index
    public IActionResult Index()
    {
        string Token = Request.Cookies["BearerToken"]!;

        var invoices = _purchaseInvoiceService.GetAll(Token);
        return View(invoices);
    }

    public IActionResult Details(int id)
    {
        string Token = Request.Cookies["BearerToken"]!;

        var invoice = _purchaseInvoiceService.GetById(id, Token);
        if (invoice == null)
        {
            return NotFound();
        }

        return View(invoice);
    }

    public IActionResult Print(int id)
    {
        string Token = Request.Cookies["BearerToken"]!;

        var invoice = _purchaseInvoiceService.PrintPurchase(id, Token);
        if (invoice is null)
            return BadRequest();

        return PhysicalFile(invoice.filePath, "application/pdf", invoice.fileName);
    }
    // GET: PurchaseInvoice/Create
    public IActionResult Create()
    {
        var model = new PurchaseInvoiceViewModel
        {
            ProductOptions = _productService.GetSelectList()
        };
        return View(model);
    }

    // POST: PurchaseInvoice/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(PurchaseInvoiceViewModel model)
    {
        string Token = Request.Cookies["BearerToken"]!;

        if (ModelState.IsValid)
        {
            var invoiceId = _purchaseInvoiceService.create(model , Token);
            if (invoiceId == null)
                return BadRequest();
            return RedirectToAction("Index"); 
        }
        return View(model);
    }

    // GET: PurchaseInvoice/Edit/5
    public IActionResult Edit(int id)
    {
        string Token = Request.Cookies["BearerToken"]!;

        var invoice = _purchaseInvoiceService.GetById(id, Token);
        if (invoice == null)
        {
            return NotFound();
        }

        return View(invoice);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(PurchaseInvoiceViewModel model)
    {
        string Token = Request.Cookies["BearerToken"]!;

        if (ModelState.IsValid)
        {
            _purchaseInvoiceService.Edit(model , Token);

            return RedirectToAction("Index");
        }

        model.ProductOptions = _productService.GetSelectList();
        return View(model);
    }


    [HttpDelete]
    public IActionResult Delete(int id)
    {
        string Token = Request.Cookies["BearerToken"]!;

        var isDeleted = _purchaseInvoiceService.Delete(id , Token);
        return isDeleted ? Ok() : BadRequest();
    }
}

Task/Views/Shared/_Layout.cshtml
@{
    var token = Context.Request.Cookies["BearerToken"]!;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskAnswer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskAnswer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskAnswer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Customer" asp-action="Customer">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="PurchaseInvoice" asp-action="Index">Purchase Invoice</a>
                        </li>
                        @if (string.IsNullOrEmpty(token))
                        {
                            <li class="nav-item ms-auto me-5">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ms-auto me-5">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="LogOut">Log Out</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TaskAnswer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>